export const mockProducts = [
  {
    _id: 'p-1',
    title: 'EchoWave Noise Cancelling Headphones',
    brand: 'Amazon Audio',
    category: 'Electronics',
    price: 149.99,
    salePrice: 119.99,
    rating: 4.6,
    reviewsCount: 1823,
    stock: 18,
    description: 'Adaptive ANC headphones with all-day battery life.',
    image:
      'https://images.unsplash.com/photo-1505740420928-5e560c06d30e?auto=format&fit=crop&w=800&q=80',
    tags: ['prime', 'wireless'],
    featured: true,
  },
  {
    _id: 'p-2',
    title: 'Kindle Paperwhite Signature Edition',
    brand: 'Amazon Devices',
    category: 'Books & Media',
    price: 189.99,
    salePrice: 169.99,
    rating: 4.8,
    reviewsCount: 982,
    stock: 33,
    description: 'Glare-free reader with wireless charging and warm light.',
    image:
      'https://images.unsplash.com/photo-1512820790803-83ca734da794?auto=format&fit=crop&w=800&q=80',
    tags: ['bestseller'],
    featured: true,
  },
  {
    _id: 'p-3',
    title: 'Smart Home Starter Kit',
    brand: 'Amazon Home',
    category: 'Smart Home',
    price: 249.99,
    salePrice: 219.99,
    rating: 4.4,
    reviewsCount: 441,
    stock: 12,
    description: 'Alexa-compatible hub, bulbs, and sensors bundle.',
    image:
      'https://images.unsplash.com/photo-1558002038-1055907df827?auto=format&fit=crop&w=800&q=80',
    tags: ['smart-home'],
    featured: true,
  },
  {
    _id: 'p-4',
    title: 'Ergonomic Mesh Office Chair',
    brand: 'Basics Pro',
    category: 'Furniture',
    price: 299.99,
    salePrice: 259.99,
    rating: 4.5,
    reviewsCount: 703,
    stock: 6,
    description: 'Breathable office chair with lumbar support and headrest.',
    image:
      'https://images.unsplash.com/photo-1580480055273-228ff5388ef8?auto=format&fit=crop&w=800&q=80',
    tags: ['workspace'],
    featured: false,
  },
  {
    _id: 'p-5',
    title: '4K Streaming Monitor 32"',
    brand: 'Aurora Displays',
    category: 'Electronics',
    price: 429.99,
    salePrice: 389.99,
    rating: 4.7,
    reviewsCount: 513,
    stock: 9,
    description: '32-inch 4K panel built for work, streaming, and gaming.',
    image:
      'https://images.unsplash.com/photo-1527443154391-507e9dc6c5cc?auto=format&fit=crop&w=800&q=80',
    tags: ['4k'],
    featured: false,
  },
  {
    _id: 'p-6',
    title: 'Travel Weekender Duffel',
    brand: 'North Urban',
    category: 'Fashion',
    price: 89.99,
    salePrice: 69.99,
    rating: 4.2,
    reviewsCount: 201,
    stock: 24,
    description: 'Water-resistant duffel with dedicated laptop sleeve.',
    image:
      'https://images.unsplash.com/photo-1542291026-7eec264c27ff?auto=format&fit=crop&w=800&q=80',
    tags: ['travel'],
    featured: false,
  },
]

export const mockOrders = [
  {
    _id: 'ord-1001',
    createdAt: '2026-03-27T09:30:00.000Z',
    status: 'Delivered',
    totalAmount: 289.98,
    shippingAddress: {
      fullName: 'Sarah Connor',
      city: 'Seattle',
      state: 'WA',
      country: 'USA',
    },
    items: [
      {
        productId: 'p-1',
        title: 'EchoWave Noise Cancelling Headphones',
        quantity: 1,
        price: 119.99,
      },
      {
        productId: 'p-6',
        title: 'Travel Weekender Duffel',
        quantity: 2,
        price: 69.99,
      },
    ],
  },
]

export const mockUsers = [
  {
    _id: 'u-1',
    name: 'Sarah Connor',
    email: 'sarah@example.com',
    role: 'customer',
    isActive: true,
  },
  {
    _id: 'u-2',
    name: 'John Admin',
    email: 'admin@example.com',
    role: 'admin',
    isActive: true,
  },
]
